# Site Settings
title: Dristanta Das
logo: "/images/logo.jpg?raw=true"
description: >
  <a href="/resume.pdf">Resume</a> | 
  <a href="https://www.linkedin.com/in/your-linkedin-username/">LinkedIn</a> | 
  <a href="https://github.com/your-github-username">GitHub</a>
  <br><br>
  Hi, I'm Dristanta Das, an Associate Data Scientist at UST. 
  I am passionate about exploring and applying cutting-edge techniques 
  to solve complex data problems.

# Theme
theme: jekyll-theme-minimal

# Analytics
google_analytics: UA-000000-0

# Optional: Additional Settings
show_downloads: true

# Social Links (if supported by theme)
github_username: your-github-username
linkedin_username: your-linkedin-username

# SEO
author: Dristanta Das
