# Site Settings
title: Dristanta Das
logo: "/images/logo.jpg?raw=true"
description: >
  <p style="text-align: center;">
  <a href="pdf/Dristanta_Das_Data_Scientist_Resume.pdf" target="_blank">Resume</a> | 
  <a href="https://www.linkedin.com/in/dasdristanta13/" target="_blank">LinkedIn</a> | 
  <a href="https://github.com/dasdristanta13" target="_blank">GitHub</a>
  </p>
  <p style="text-align: center;">
  Hi, I'm Dristanta Das, an Assistant Manager â€“ Data Science at Genpact, specializing in LLM-based systems, NLP, and AI automation. 
  I design and deploy scalable Text-to-SQL, RAG, and agentic AI solutions using frameworks like LangChain, LangGraph, and PyTorch. 
  Previously at UST, I developed NLP-driven search and anomaly detection systems that improved operational efficiency and data reliability. 
  My focus lies in building robust, production-ready AI solutions that drive measurable business impact.
  </p>

# Theme
theme: jekyll-theme-minimal

# Analytics
google_analytics: UA-000000-0

# Optional: Additional Settings
show_downloads: false

# Social Links (if supported by theme)
github_username: dasdristanta13
linkedin_username: dasdristanta13

# SEO
author: Dristanta Das
